name: Deploy via SFTP

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Deploy to server via SFTP
      uses: wlixcc/SFTP-Deploy-Action@v1.2.4
      with:
        username: ${{ secrets.SFTP_USER }}
        server: ${{ secrets.SFTP_HOST }}
        port: ${{ secrets.SFTP_PORT }}

    - name: Install SSH Key
      uses: shimataro/ssh-key-action@v2  
      with:
        key:
          privateKey: ${{ secrets.SFTP_PRIVATE_KEY }}
          known_hosts: 'just-a-placeholder-so-we-dont-get-errors'
          local_path: './'  # Folder to upload
          remote_path: '/uploads'  # Path on server
          sftp_only: true
