name: Deploy via SFTP

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install SSH Key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.SFTP_PRIVATE_KEY }}
        name: id_rsa
        known_hosts: 'just-a-placeholder'  # Required, even if SFTP only
        if_key_exists: replace

    - name: Deploy to server via SFTP
      uses: wlixcc/SFTP-Deploy-Action@v1.2.4
      with:
        username: ${{ secrets.SFTP_USER }}
        server: ${{ secrets.SFTP_HOST }}
        port: ${{ secrets.SFTP_PORT }}
        local_path: './'
        remote_path: '/uploads'
        sftp_only: true
